GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Go to Coop"
}

###

DELETE http://localhost:3001/todo/DELETE/66185be946dea37deeefe8f1

###

PUT http://localhost:3001/todo/complete/661d30171f464866fde32f53